import React from "react";
import { useLang } from "../lib/i18n.jsx";

// Юридические тексты сайта. Обновлены 15.09.2026 под текущий продукт:
// монеты за акции с выплатами холдерам, зап (оплата ETH), ИИ-агент, доска
// идей, чат с ИИ монеты; разделы про котов, кейсы, кликер, арену и казну
// выкупа убраны вместе с самими функциями. Генератор: scratchpad/legal_gen.py
// (Claude); при правках держать RU и EN синхронными.

function Doc({ title, updated, sections }) {
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", paddingBottom: 70 }}>
      <div className="page-title">{title}</div>
      <div className="page-sub">{updated}</div>
      {sections.map(([h, body], i) => (
        <div key={i} style={{ marginTop: 26 }}>
          <h3 style={{ fontSize: 17, margin: "0 0 8px" }}>{h}</h3>
          <p className="dim" style={{ margin: 0, fontSize: 14, lineHeight: 1.7 }}>{body}</p>
        </div>
      ))}
    </div>
  );
}

export function Privacy() {
  const { lang } = useLang();
  if (lang === "en") {
    return (
      <Doc
        title="Privacy Policy"
        updated="Effective date: September 15, 2026 · applies to the hood web interface"
        sections={[
          ["1. About this Policy",
           "This Policy describes how the operator of the hood platform (\"hood\", \"we\") handles information in connection with the hood web interface and its community and AI features. hood is a non-custodial interface to smart contracts on Robinhood Chain: we never hold your assets or keys, and the site works without accounts or registration. By using the interface you acknowledge this Policy."],
          ["2. Information We Collect",
           "We do not ask for and do not collect names, postal addresses, phone numbers, emails or identity documents. The information that may be processed is limited to: public wallet addresses you interact with; content you voluntarily submit (token names, descriptions, images and links, chat messages, ideas and votes on a coin's idea board, messages to a coin's AI); signatures you create with your wallet to confirm that a message, idea or vote is yours (they contain no secrets and cannot move funds); on-chain records of your transactions; and standard technical data (such as IP address and browser type) that any web request unavoidably exposes to infrastructure providers."],
          ["3. Sources of Information",
           "Information comes from three sources only: directly from you (content you type or upload); automatically from your browser when it requests pages and APIs; and from public blockchains, where your transactions are recorded by the network itself and are readable by anyone."],
          ["4. How We Use Information",
           "Information is used solely to operate the interface: displaying tokens and trades, verifying wallet interactions and signatures, showing chats and idea boards, generating the answers of a coin's AI and the pages its agent builds, maintaining the security, stability and usage limits of the service, moderating obviously unlawful content, and complying with legal obligations. We do not build behavioral profiles and do not use your data for advertising."],
          ["5. Legal Bases",
           "Where data-protection law requires a legal basis, we rely on: performance of the service you request (showing the interface and your on-chain data), our legitimate interest in keeping the platform secure and functional, your consent where you voluntarily submit content, and compliance with legal obligations."],
          ["6. Blockchain Information",
           "Robinhood Chain is a public network. Every transaction — launching a token, trading, enabling a coin's AI, claiming fees or holder payouts — is permanently recorded on-chain together with your wallet address and is visible to anyone through any explorer. hood does not control the network and cannot edit, hide or delete on-chain records. Consider this carefully before transacting: blockchain publicity is irreversible by design."],
          ["7. How We Disclose Information",
           "We do not sell personal information and do not share it for advertising. Information may be disclosed only to infrastructure providers that make the service work (hosting, the API gateway, RPC nodes, indexers, database, explorer and price APIs), to AI model providers when you use AI features (section 10), where required by applicable law or a valid legal request, or to protect the rights, security and integrity of the platform and its users."],
          ["8. Third-Party Services",
           "The interface interacts with independent services: your wallet software; Robinhood Chain RPC nodes, including a dedicated RPC provider; the Blockscout explorer API; an indexer of on-chain events; public exchange-rate APIs; decentralized-exchange contracts used when ETH is converted into a coin's quote asset; GitHub Pages for hosting; Cloudflare, which runs the API behind the coin AI chat; Google Firebase for storing chats and idea boards; OpenRouter and the AI model providers it routes requests to; and image CDNs for company and model logos. Each operates under its own privacy policy and sees your IP address as with any web request. We are not responsible for their practices — review their policies separately."],
          ["9. Cookies and Browser Storage",
           "hood does not use tracking cookies. Your browser's localStorage keeps interface preferences (language, theme, panel layout, slippage), a random guest name for the public chat, favourites, drafts of a token launch, small caches (the token list, the last view of a token page, creation dates) and — after you sign in to a coin's AI chat — a signed proof of wallet ownership valid for seven days. Nothing in local storage is sent to us beyond what the corresponding feature needs to work, and clearing browser data erases it. Blocking storage may limit some features."],
          ["10. AI Features",
           "Some coins have an AI agent and an AI chat. When you write to a coin's AI, your message, your wallet address, the recent messages of that chat and public information about the coin (its description, links, the agent's builds and idea-board entries) are sent through OpenRouter to the third-party model provider that the coin's creator chose; the answer is stored in the chat, which is visible to everyone who opens the coin's page. The same applies to ideas submitted to the idea board: the agent turns the leading idea into a page using a third-party model, and the resulting page is published on hoodandarrow.com. Model providers process this data under their own policies and may retain it for abuse monitoring; we do not use your messages to train models. Do not put personal information into AI chats or ideas — treat everything you type there as public. To keep the chat usable for everyone we count messages per wallet and per coin and may decline messages over the limit; these counters contain only wallet and coin addresses."],
          ["11. Retention",
           "Off-chain content (public chat messages, AI chat messages, idea-board entries and votes) is kept as long as it is needed for the feature to function and may be removed at the platform's discretion, or on your request where the law requires it. Local settings live in your browser until you clear them. On-chain records are permanent and outside anyone's control — including ours."],
          ["12. Security",
           "We apply reasonable safeguards appropriate for a static, non-custodial interface, and the most important one is architectural: hood never receives your private keys, seed phrases or funds, so they cannot leak from us. Never share your seed phrase or private key with anyone — no one acting on behalf of hood will ever ask for them. No internet service can guarantee absolute security."],
          ["13. International Processing",
           "The interface is served globally and infrastructure providers may process technical data in different jurisdictions with different data-protection laws (for example, the chat database is hosted in the EU, the chat API runs on Cloudflare's global network, and AI model providers may process requests in the United States). Where required, appropriate safeguards apply. Public blockchain data is replicated worldwide by the nature of the network."],
          ["14. Your Rights and Choices",
           "Depending on your jurisdiction, you may have rights to access, correct or delete personal information, object to or restrict processing, and withdraw consent. For off-chain data (such as chat messages, AI-chat messages or idea-board entries) contact us and we will respond within a reasonable time. Note: on-chain data cannot be altered or erased by anyone — this technical limitation applies to all blockchain platforms."],
          ["15. Jurisdiction-Specific Disclosures",
           "We do not sell or \"share\" personal information as defined by applicable privacy laws, do not use it for cross-context behavioral advertising and do not process it for automated decision-making with legal effects. Residents of jurisdictions with specific privacy statutes may exercise their statutory rights through the contact below without discrimination."],
          ["16. Children",
           "The interface is not directed at children and is not intended for persons under 18 years of age (or the age of majority in your jurisdiction). We do not knowingly collect information from minors. If you believe a minor has used the interface, contact us."],
          ["17. Policy Changes",
           "We may update this Policy as the product evolves. The current version with its effective date is always available on this page; material changes may additionally be announced in the interface. Continued use after changes take effect constitutes acceptance."],
          ["18. Contact",
           "Questions, privacy requests and complaints regarding this Policy can be sent to the platform operator: contact@hoodandarrow.com. We will make reasonable efforts to respond promptly."],
        ]}
      />
    );
  }
  return (
    <Doc
      title="Политика конфиденциальности"
      updated="Действует с: 15 сентября 2026 · относится к веб-интерфейсу hood"
      sections={[
        ["1. Об этой политике",
         "Эта Политика описывает, как оператор платформы hood («hood», «мы») обращается с информацией при работе веб-интерфейса hood, его комьюнити-функций и функций ИИ. hood — некастодиальный интерфейс к смарт-контрактам в сети Robinhood Chain: мы никогда не храним ваши активы и ключи, а сайт работает без аккаунтов и регистрации. Используя интерфейс, вы принимаете эту Политику."],
        ["2. Какую информацию мы собираем",
         "Мы не запрашиваем и не собираем имена, адреса, телефоны, почту и документы. Обрабатываемая информация ограничена: публичными адресами кошельков, с которыми вы работаете; контентом, который вы добровольно публикуете (названия, описания, картинки и ссылки токенов, сообщения чата, идеи и голоса на доске идей монеты, сообщения ИИ монеты); подписями, которые вы создаёте кошельком, чтобы подтвердить, что сообщение, идея или голос ваши (они не содержат секретов и не могут двигать средства); ончейн-записями ваших транзакций; и стандартными техническими данными (IP-адрес, тип браузера), которые любой веб-запрос неизбежно открывает инфраструктурным провайдерам."],
        ["3. Источники информации",
         "Информация поступает только из трёх источников: напрямую от вас (то, что вы вводите или загружаете); автоматически от вашего браузера при запросах к страницам и API; и из публичных блокчейнов, где ваши транзакции записывает сама сеть — читать их может кто угодно."],
        ["4. Как мы используем информацию",
         "Информация используется исключительно для работы интерфейса: отображение токенов и сделок, проверка взаимодействий кошелька и подписей, показ чатов и досок идей, генерация ответов ИИ монеты и страниц, которые строит её агент, поддержание безопасности, стабильности и лимитов использования сервиса, модерация явно противоправного контента и соблюдение требований закона. Мы не строим поведенческие профили и не используем данные для рекламы."],
        ["5. Правовые основания",
         "Там, где закон о защите данных требует правового основания, мы опираемся на: исполнение запрошенного вами сервиса (отображение интерфейса и ваших ончейн-данных), законный интерес в безопасности и работоспособности платформы, ваше согласие при добровольной публикации контента и соблюдение юридических обязательств."],
        ["6. Данные в блокчейне",
         "Robinhood Chain — публичная сеть. Каждая транзакция — запуск токена, сделка, включение ИИ монеты, клейм комиссий или выплат холдерам — навсегда записывается в блокчейн вместе с адресом вашего кошелька и видна любому через эксплорер. hood не управляет сетью и не может изменить, скрыть или удалить ончейн-записи. Учитывайте это до отправки транзакции: публичность блокчейна необратима по построению."],
        ["7. Как мы раскрываем информацию",
         "Мы не продаём персональную информацию и не передаём её для рекламы. Раскрытие возможно только инфраструктурным провайдерам, обеспечивающим работу сервиса (хостинг, API-шлюз, RPC-узлы, индексаторы, база данных, API эксплорера и курсов), провайдерам моделей ИИ, когда вы пользуетесь функциями ИИ (раздел 10), по требованию применимого закона или законного запроса органов, а также для защиты прав, безопасности и целостности платформы и её пользователей."],
        ["8. Сторонние сервисы",
         "Интерфейс взаимодействует с независимыми сервисами: вашим кошельком; RPC-узлами Robinhood Chain, включая выделенного RPC-провайдера; API эксплорера Blockscout; индексатором ончейн-событий; публичными API курсов; контрактами децентрализованной биржи, через которые ETH меняется на валюту монеты; хостингом GitHub Pages; Cloudflare, на котором работает API чата с ИИ монеты; Google Firebase для хранения чатов и досок идей; OpenRouter и провайдерами моделей ИИ, которым он передаёт запросы; CDN с логотипами компаний и моделей. Каждый работает по собственной политике конфиденциальности и видит ваш IP-адрес, как при любом веб-запросе. Мы не отвечаем за их практики — ознакомьтесь с их политиками отдельно."],
        ["9. Cookies и хранилище браузера",
         "hood не использует трекинговые cookies. В localStorage вашего браузера хранятся настройки интерфейса (язык, тема, расположение панелей, проскальзывание), случайное гостевое имя для общего чата, избранное, черновики запуска токена, небольшие кэши (список токенов, последний вид страницы монеты, даты создания) и — после входа в чат с ИИ монеты — подписанное подтверждение владения кошельком сроком на семь дней. Из локального хранилища нам не уходит ничего сверх того, что нужно соответствующей функции, а очистка данных браузера удаляет его. Блокировка хранилища может ограничить часть функций."],
        ["10. Функции ИИ",
         "У части монет есть ИИ-агент и чат с ИИ. Когда вы пишете ИИ монеты, ваше сообщение, адрес кошелька, последние сообщения этого чата и публичная информация о монете (описание, ссылки, сборки агента и записи доски идей) отправляются через OpenRouter стороннему провайдеру модели, которую выбрал создатель монеты; ответ сохраняется в чате, который видит каждый, кто открывает страницу монеты. То же относится к идеям на доске: агент превращает лидирующую идею в страницу с помощью сторонней модели, и получившаяся страница публикуется на hoodandarrow.com. Провайдеры моделей обрабатывают эти данные по собственным политикам и могут хранить их для контроля злоупотреблений; мы не используем ваши сообщения для обучения моделей. Не пишите в чаты с ИИ и в идеи персональные данные — считайте всё введённое там публичным. Чтобы чат оставался доступным для всех, мы считаем сообщения по кошельку и по монете и можем отклонять сообщения сверх лимита; в этих счётчиках только адреса кошелька и монеты."],
        ["11. Сроки хранения",
         "Офчейн-контент (сообщения общего чата, сообщения чата с ИИ, записи и голоса на доске идей) хранится, пока это нужно для работы функции, и может удаляться по усмотрению платформы или по вашему запросу там, где этого требует закон. Локальные настройки живут в вашем браузере, пока вы их не очистите. Ончейн-записи постоянны и не подконтрольны никому — включая нас."],
        ["12. Безопасность",
         "Мы применяем разумные меры защиты, соответствующие статическому некастодиальному интерфейсу, и главная из них — архитектурная: hood никогда не получает ваши приватные ключи, сид-фразы и средства, поэтому они не могут утечь от нас. Никогда и никому не сообщайте сид-фразу или приватный ключ — никто от имени hood их не попросит. Ни один интернет-сервис не может гарантировать абсолютную безопасность."],
        ["13. Международная обработка",
         "Интерфейс доступен глобально, и инфраструктурные провайдеры могут обрабатывать технические данные в разных юрисдикциях с разными законами о защите данных (например, база чата размещена в ЕС, API чата работает в глобальной сети Cloudflare, а провайдеры моделей ИИ могут обрабатывать запросы в США). Где это требуется, применяются соответствующие гарантии. Данные публичного блокчейна реплицируются по всему миру по самой природе сети."],
        ["14. Ваши права и выбор",
         "В зависимости от юрисдикции у вас могут быть права на доступ к персональной информации, её исправление и удаление, возражение против обработки и её ограничение, а также отзыв согласия. По офчейн-данным (например, сообщениям чатов, чата с ИИ или записям доски идей) свяжитесь с нами — мы ответим в разумный срок. Важно: ончейн-данные не может изменить или стереть никто — это техническое ограничение относится ко всем блокчейн-платформам."],
        ["15. Раскрытия для отдельных юрисдикций",
         "Мы не продаём и не «передаём» персональную информацию в значении применимых законов о приватности, не используем её для кросс-контекстной поведенческой рекламы и не принимаем на её основе автоматизированных решений с юридическими последствиями. Жители юрисдикций со специальными законами о приватности могут реализовать свои права через контакт ниже без какой-либо дискриминации."],
        ["16. Дети",
         "Интерфейс не адресован детям и не предназначен для лиц младше 18 лет (или возраста совершеннолетия в вашей юрисдикции). Мы сознательно не собираем информацию о несовершеннолетних. Если вы считаете, что интерфейсом воспользовался несовершеннолетний, свяжитесь с нами."],
        ["17. Изменения политики",
         "Мы можем обновлять эту Политику по мере развития продукта. Актуальная версия с датой вступления в силу всегда доступна на этой странице; о существенных изменениях мы можем дополнительно сообщить в интерфейсе. Продолжение использования после вступления изменений в силу означает согласие с ними."],
        ["18. Контакты",
         "Вопросы, запросы по приватности и жалобы по этой Политике направляйте оператору платформы: contact@hoodandarrow.com. Мы приложим разумные усилия, чтобы ответить оперативно."],
      ]}
    />
  );
}

export function Terms() {
  const { lang } = useLang();
  if (lang === "en") {
    return (
      <Doc
        title="Terms of Use"
        updated="Effective date: September 15, 2026 · hood on Robinhood Chain mainnet"
        sections={[
          ["1. Agreement",
           "These Terms are a binding agreement between you and the operator of the hood platform (\"hood\", \"we\") governing your use of the hood web interface and related community features. By accessing or using the interface you accept these Terms and the Privacy Policy. If you do not agree, do not use the interface. These Terms contain a binding individual-arbitration provision and a class-action waiver (section 34) and important limitations of our liability (section 29) — please read them carefully."],
          ["2. About hood",
           "hood is a software interface that lets you interact with autonomous smart contracts on Robinhood Chain: launch tokens with a fixed supply, trade them on bonding curves priced in ETH or in a third-party tokenized stock or stablecoin, receive the programmed holder payouts of such tokens, enable an optional AI agent for a coin you created, take part in a coin's idea board and AI chat, and view analytics. hood is not a broker, dealer, exchange, custodian, money transmitter, financial institution or investment adviser, and provides no such services. The platform operates on Robinhood Chain mainnet, where tokens are traded using assets that have real monetary value; transactions are real and irreversible. The smart contracts have NOT undergone a formal independent third-party security audit. Software may contain bugs, and you use the platform at your own risk with funds you can afford to lose entirely."],
          ["3. Eligibility",
           "You may use the interface only if you are at least 18 years old (or the age of majority in your jurisdiction), have full legal capacity, and access it from, and are a resident of, a jurisdiction where such use is lawful. You represent that you are not subject to sanctions administered or enforced by any relevant authority (including OFAC, UN, EU or UK designations) and are not on any prohibited-parties list. You are responsible for ensuring that using the interface is legal for you."],
          ["4. Prohibited Jurisdictions",
           "The interface is not offered to, and may not be used by, any person who is a citizen, resident of, or located in the United States of America or any U.S. territory, or in any country or region subject to comprehensive sanctions (including, without limitation, Cuba, Iran, North Korea, Syria, and the Crimea, Donetsk and Luhansk regions), or any other jurisdiction where accessing the interface or trading these tokens is prohibited or would require registration or licensing we do not hold (\"Prohibited Jurisdictions\"). You must not use a VPN, proxy or any other means to disguise your location in order to access the interface from a Prohibited Jurisdiction. We may block access from any jurisdiction at our discretion."],
          ["5. No Investment Advice; Not an Offering",
           "Nothing on the platform is investment, financial, legal, tax or accounting advice, a recommendation, solicitation, or an offer to buy or sell any asset, and nothing constitutes a prospectus, offering document or registered offering of securities. Tokens launched through hood are created by users, not by hood, and are not endorsed, vetted, guaranteed or backed by hood. Rankings, analytics, \"trending\" placement and any interface prominence are informational only and are not endorsements. You alone are responsible for evaluating the merits and risks of any transaction and should consult your own qualified advisers."],
          ["6. Speculative Assets — No Intrinsic Value",
           "Tokens launched and traded through hood are highly speculative digital collectibles with no intrinsic value and no rights to any ownership, equity, revenue or claim against hood, its operator or any other person. Where a token's trading pair is programmed to pass a share of trading fees to its holders (section 18), that is a mechanical feature of the smart contract, funded solely by trading that may never happen, and not a promise of profit, income or return. Most such tokens lose all or nearly all of their value, often rapidly. Their price can go to zero at any time. Do not purchase any token unless you are financially able and willing to lose the entire amount. You accept full responsibility for your trading decisions and outcomes."],
          ["7. Non-Custodial Interface",
           "hood never holds, controls or has access to your assets, private keys or wallets. All operations are executed by smart contracts on the blockchain and initiated by you through your own wallet. We cannot execute, reverse, block or expedite transactions on your behalf. You are not our customer and no fiduciary, agency, advisory or trust relationship arises between you and hood."],
          ["8. Wallets and Security",
           "You are solely responsible for the security of your wallet, private keys and seed phrase. hood never asks for them — anyone who does is a scammer. Any action signed by your wallet is deemed your action; we are not liable for losses caused by compromised wallet access, phishing, malware or your own error."],
          ["9. Transactions",
           "Review every transaction — addresses, amounts, network — before signing. Prices and quotes in the interface are estimates: the final result is determined by the smart contract at execution time and may differ (including due to other users' transactions, slippage or front-running). Blockchain transactions are irreversible once confirmed and cannot be cancelled or refunded by anyone, including hood. When you pay in ETH for a token whose curve is priced in another asset, a helper contract first swaps your ETH for that asset on a third-party decentralized exchange and then trades on the curve within the same transaction (and the reverse when you sell); the amount you receive depends on that exchange's liquidity at execution time, and the estimates the interface shows converted into ETH and US dollars are for convenience only."],
          ["10. Token Launches and Content",
           "When you launch a token you are solely responsible for its name, ticker, description, image and links, and you confirm that you hold the necessary rights to them and that they do not infringe any third party's rights, impersonate any person or brand, or violate any law. Token metadata is written to the public blockchain permanently and cannot be edited or deleted by anyone, including hood. We may moderate off-chain content (such as chat) and hide interface listings that violate these Terms, but we cannot alter on-chain records. Pages that a coin's AI agent builds from holders' ideas are hosted by hood and may be edited, hidden or removed at our discretion."],
          ["11. Bonding Curve Trading and Graduation",
           "Tokens trade on an automated bonding curve until they reach the graduation threshold, after which liquidity migrates to a decentralized exchange and is locked. Tokens may have little or no liquidity, may be extremely volatile and may become worthless. hood does not guarantee graduation, liquidity, market depth, tradability or any price level of any token."],
          ["12. Risk Disclosures",
           "By using the interface you accept the risks of blockchain technology, including: total loss of assets; defects or vulnerabilities in smart contracts (which have not undergone a formal independent audit); failures, congestion, forks or reorganizations of networks, wallets and infrastructure; inaccurate or delayed market data; errors, bias or harmful content in the outputs of AI models; scams, rug-pulls and abusive conduct by other users or token creators; regulatory uncertainty and future legal changes; and tax consequences of your operations. Use the interface only if you understand and accept these risks."],
          ["13. Fees, Taxes and No Refunds",
           "Every trade on a curve pays a protocol fee (currently 1% of the trade) that the smart contract splits automatically: a share goes to the token's creator, a share goes to the arena treasury, and the rest to the team; where the creator has enabled the coin's AI agent, a part of the fee funds that agent's budget instead of going to the creator. The split is fixed in each trading pair when the token is created and does not change afterwards; tokens created under earlier settings keep their original split. The current split for new launches is always shown on the launch page and on each token's page. For tokens priced in a tokenized stock or stablecoin the creator may additionally set, at launch, a holder-payout rate of up to 3% of each trade (section 18). You also pay network gas fees and, when paying in ETH for a token priced in another asset, the fees and price impact of the decentralized exchange used for the conversion. All fees are final and non-refundable. The arena treasury is a smart contract with no withdrawal function: its balance can only be spent on buying platform tokens off the market and burning them. Once a day an automated bot distributes the accumulated balance among the previous day's podium of the Arena (a daily tournament ranked by fair on-chain trading volume, computed by open code from on-chain trades) in the proportions shown on the Arena page; a payout may be delayed or skipped when market data is unavailable or a token's curve is closed, in which case the balance carries over. Buybacks are not payments to any person, are not guaranteed and create no claim against hood. You are solely responsible for determining, reporting and paying any taxes arising from your operations."],
          ["14. Acceptable Use",
           "You must not use the interface to: violate any applicable law; commit fraud or mislead users; infringe intellectual property or impersonate others; interfere with, attack, overload or reverse-engineer the interface or contracts; manipulate markets (including wash trading, spoofing and coordinated pumping or \"rug pulls\"); launder money or finance illegal or terrorist activity; or launch or trade tokens that constitute securities, derivatives or other regulated instruments in relevant jurisdictions. You must not use bots or automated means to abuse the interface."],
          ["15. Compliance and Anti-Money-Laundering",
           "hood does not facilitate money laundering, sanctions evasion or terrorist financing and does not knowingly deal with sanctioned persons. You represent that the funds you use are lawfully obtained and that your use complies with all anti-money-laundering, counter-terrorist-financing and sanctions laws that apply to you. We may use screening tools and may restrict or decline to serve wallet addresses associated with sanctioned parties, illicit activity or elevated risk, and may report activity to authorities where required by law."],
          ["16. Platform Interests and Conflicts",
           "The team receives a share of protocol fees set in the smart contracts. hood and its team members may launch, hold, buy or sell tokens on the platform, including tokens created by the team, and may enable AI agents for them. Budgets accumulated for AI agents are spent on running those agents at the platform's discretion; we may pay for AI features from our own funds and may stop doing so at any time. Interface features may be added, changed, hidden or retired at any time. Nothing in the interface — rankings, featured placement, analytics or the mere presence of a feature — is a recommendation or a promise of any future action by hood."],
          ["17. Launches Priced in Tokenized Stocks",
           "The platform may allow tokens to be launched and traded on a bonding curve priced in a third-party tokenized stock or stablecoin rather than in the native coin. Such quote assets are issued and administered by third parties with whom hood has no relationship. hood is not affiliated with, sponsored by, endorsed by or connected to Robinhood Markets, Inc., any of its affiliates, any stock exchange, any listed company, or any issuer of a tokenized stock; product, company and ticker names are trademarks of their respective owners and are used solely to identify the relevant asset. Buying a token whose curve is priced in a tokenized stock is not buying that stock or any interest in the underlying company: it conveys no shareholder, voting, dividend or economic rights in that company. You additionally accept the risks of the quote asset itself, including issuer or custodian default, redemption or transfer restrictions, depegging from the underlying price, oracle failure, delisting, trading halts and regulatory action. In many jurisdictions tokenized stocks are regulated instruments whose acquisition, holding or trading may be restricted or require licensing; you are solely responsible for determining whether your use is lawful for you, and you must not use the feature if it is not."],
          ["18. Holder Payouts",
           "A token whose curve is priced in a tokenized stock or stablecoin may be launched with a holder-payout rate chosen by its creator (0–3% of each trade). That share of every buy and sell is set aside by the token contract and credited to holders in proportion to their balances, in the quote asset of that token (for example a tokenized stock), not in ETH; the interface may display it converted into ETH and US dollars for convenience. Credited amounts can be claimed by the holder in the interface, and an automated service of the platform may also pay them out to holders' wallets on a best-effort basis — runs may be delayed, skipped or discontinued, and nothing is owed to you if they are. Payouts exist only while trading happens: with no trades there is nothing to distribute, and the amount can be zero for any period. They are a programmed feature of the trading pair — not a dividend, interest, yield or return on investment, not a payment by hood, and not a distribution by, or a right against, the company whose stock the quote asset tracks. Holding the token conveys no shareholder, voting or economic rights in that company. You are solely responsible for determining whether acquiring, holding or receiving such assets is lawful for you and for any tax consequences."],
          ["19. The Coin's AI Agent and Idea Board",
           "The creator of a token may enable an AI agent for it by signing an on-chain transaction; this choice is permanent and, from that moment, part of the protocol fee that would otherwise go to the creator funds the agent's budget (section 13). Holders of such a token may propose ideas on the coin's idea board and vote for them with the weight of their balance; an automated agent periodically takes the leading idea and builds a web page from it using a third-party AI model chosen by the creator, publishing the result on hoodandarrow.com. Ideas and votes are signed with your wallet and are public. The agent runs on a best-effort basis: builds may fail, be delayed, be skipped when the budget is exhausted, or turn out different from what was proposed; we may set limits, require a budget, change the model, decline or remove any idea or page, and suspend the feature at any time. AI outputs are generated automatically, are not reviewed by hood, may be wrong, misleading, infringing or offensive, and are not statements, advice or recommendations of hood. Budgets accumulated for an agent serve the operation of that agent and are not your property or claim."],
          ["20. Chat with the Coin's AI",
           "Where a coin's AI is enabled, holders of that coin may talk to it in a chat that is public: everyone who opens the coin's page can read every message together with the wallet address of its author. To write you sign a message with your wallet confirming ownership; no transaction or payment is required. Your messages and public information about the coin are sent to a third-party AI model provider to generate the answer (see the Privacy Policy). The AI speaks in the voice of a meme coin: its answers are entertainment and general information — not financial, legal or tax advice, not statements of fact about the token, its price or its prospects, and not commitments of hood or of the coin's creator. Do not act on them without your own verification. We apply usage limits per wallet and per coin, may moderate, hide or delete messages, restrict wallets that abuse the chat, and change or discontinue the feature at any time. Do not post personal information, keys or anything you would not publish openly."],
          ["21. Activity Limits",
           "We may introduce limits on transaction size or frequency, or restrict certain interface features, for security, risk-management or legal-compliance reasons. On-chain limits (such as the creator's maximum initial buy) are enforced by the contracts themselves."],
          ["22. Third-Party Services",
           "The interface relies on independent services: wallets, RPC nodes, the block explorer, an event indexer, price APIs, decentralized-exchange contracts, hosting, the API gateway that serves the coin AI chat, the chat database and the AI model providers reached through OpenRouter. Their availability, accuracy and terms are outside our control; integration does not mean endorsement. Your use of third-party services is governed by their own terms, and we are not responsible for their acts or omissions."],
          ["23. Intellectual Property and Complaints",
           "The interface, its design, texts and code are protected by law. You are granted a limited, non-exclusive, non-transferable, revocable licence to access and use the interface for lawful purposes only; all other rights are reserved. If you believe content displayed through the interface infringes your intellectual-property rights or impersonates you, send a notice to the contact in section 37 identifying the content, your rights and your contact details, and we will review and, where appropriate, remove the off-chain listing (on-chain data cannot be altered). We may remove content and disable access for repeat infringers."],
          ["24. Submitted Content",
           "You retain your rights to content you submit (token metadata, chat messages, ideas for a coin's agent, messages to a coin's AI). By submitting it you grant hood a worldwide, royalty-free, sublicensable licence to host, reproduce and display that content for the operation and promotion of the platform. You are solely responsible for your content. Content written to the blockchain is public and permanent by nature."],
          ["25. Feedback",
           "If you send us ideas, suggestions or bug reports, we may use them without restriction or compensation to improve the platform."],
          ["26. Service Availability",
           "We may change, suspend or discontinue any part of the interface at any time without notice or liability. We do not guarantee continuous, uninterrupted or error-free operation. Smart contracts remain on the blockchain regardless of the interface's availability."],
          ["27. No Warranties",
           "The interface is provided \"as is\" and \"as available\", with all faults. To the maximum extent permitted by law we disclaim all warranties, express, implied or statutory, including merchantability, fitness for a particular purpose, title, non-infringement, accuracy of data and uninterrupted or secure operation. We do not warrant that any token has value, liquidity or a market. Analytical features — including \"fair volume\", wallet badges (such as \"sniper\", \"wash trading\", \"whale\" or \"fresh wallet\"), the token passport and creator reputation — are automated heuristics computed from public on-chain data for informational purposes only. They may be incomplete, delayed or wrong in either direction, are not accusations of wrongdoing against any person, are not investment research or advice, and must not be relied upon for trading decisions. Outputs of AI features are likewise automated and unverified."],
          ["28. Assumption of Risk",
           "You knowingly and voluntarily assume all risks arising from your use of the interface, the smart contracts, the blockchain network and any token, and you agree that hood is not responsible for any loss you suffer as a result. This assumption of risk survives termination of these Terms."],
          ["29. Limitation of Liability",
           "To the maximum extent permitted by law, hood and its contributors are not liable for indirect, incidental, special, punitive or consequential damages, or loss of profits, data, goodwill or assets, arising from or related to use of the interface, contracts, network, tokens or third-party services, even if advised of the possibility. Our aggregate liability for all claims is limited to the greater of the protocol fees you paid to the team over the preceding 12 months or 100 USD. Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you."],
          ["30. Indemnification",
           "You agree to indemnify and hold harmless hood and its contributors against claims, losses, liabilities and expenses (including reasonable legal fees) arising from your use of the interface, your content, your tokens, your violation of these Terms or of applicable law, or your infringement of any third-party right. Disputes between users, or between you and a token creator, are resolved between those parties; you release hood from claims related to such disputes."],
          ["31. Force Majeure",
           "hood is not liable for any failure or delay caused by events beyond our reasonable control, including acts of God, natural disasters, war, terrorism, civil unrest, labour disputes, changes in law, governmental or regulatory action, network or blockchain failures, forks, congestion, exploits, outages of internet, hosting, RPC or third-party services, and power failures."],
          ["32. Termination and Restriction of Access",
           "We may restrict or terminate your access to the interface at any time without notice in case of fraud, market manipulation, sanctions or legal risk, violation of these Terms or a security threat. Restricting interface access does not affect your on-chain assets, which remain under the control of your wallet. Sections that by their nature should survive (including risk disclosures, disclaimers, limitations of liability, indemnification and dispute resolution) survive termination."],
          ["33. Governing Law",
           "These Terms and any dispute arising from them or from your use of the interface are governed by the law applicable at the operator's location, without regard to conflict-of-law rules, unless mandatory consumer-protection rules of your jurisdiction provide otherwise."],
          ["34. Dispute Resolution; Arbitration and Class-Action Waiver",
           "Before bringing any formal claim you agree to first attempt good-faith resolution by contacting us (section 37) and allowing 60 days. Any dispute not resolved that way shall, to the maximum extent permitted by law, be settled by final and binding individual arbitration rather than in court, except that either party may seek relief in a small-claims court or seek injunctive relief for intellectual-property or unauthorized-access matters. YOU AND HOOD AGREE THAT CLAIMS MAY BE BROUGHT ONLY IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS, COLLECTIVE OR REPRESENTATIVE PROCEEDING, AND THAT NO ARBITRATION OR CLAIM SHALL BE CONSOLIDATED WITH ANY OTHER. Any claim must be brought within one year after it arises, or it is permanently barred, to the extent allowed by law."],
          ["35. General Terms",
           "If any provision of these Terms is held unenforceable, it shall be limited or severed to the minimum extent necessary and the remainder stays in full effect. Our failure to enforce any right is not a waiver. You may not assign your rights under these Terms without our consent; we may assign ours in connection with operating or transferring the platform. Headings are for convenience only. These Terms and the Privacy Policy are the entire agreement between you and hood regarding the interface."],
          ["36. Changes to these Terms",
           "We may update these Terms as the product evolves. The current version with its effective date is always available on this page; material changes may additionally be announced in the interface. Continued use after the effective date constitutes acceptance."],
          ["37. Contact",
           "Questions about these Terms, and intellectual-property or compliance notices: contact@hoodandarrow.com."],
        ]}
      />
    );
  }
  return (
    <Doc
      title="Условия использования"
      updated="Действует с: 15 сентября 2026 · hood в основной сети Robinhood Chain"
      sections={[
        ["1. Соглашение",
         "Эти Условия — обязывающее соглашение между вами и оператором платформы hood («hood», «мы»), регулирующее использование веб-интерфейса hood и комьюнити-функций. Получая доступ к интерфейсу, вы принимаете эти Условия и Политику конфиденциальности. Если вы не согласны — не используйте интерфейс. Эти Условия содержат оговорку об обязательном индивидуальном арбитраже и отказ от коллективных исков (раздел 34), а также важные ограничения нашей ответственности (раздел 29) — внимательно с ними ознакомьтесь."],
        ["2. О hood",
         "hood — программный интерфейс для взаимодействия с автономными смарт-контрактами в сети Robinhood Chain: запуск токенов с фиксированным сапплаем, торговля на бондинг-кривых с ценой в ETH или в сторонней токенизированной акции либо стейблкоине, получение запрограммированных выплат холдерам таких токенов, включение необязательного ИИ-агента для созданной вами монеты, участие в доске идей и чате с ИИ монеты, просмотр аналитики. hood не является брокером, дилером, биржей, кастодианом, оператором переводов, финансовой организацией или инвестиционным консультантом и не оказывает таких услуг. Платформа работает в основной сети Robinhood Chain, где токены торгуются за активы, имеющие реальную денежную стоимость; транзакции реальны и необратимы. Смарт-контракты НЕ проходили формальный независимый аудит безопасности. В программном обеспечении могут быть ошибки; вы используете платформу на свой риск и только на средства, которые готовы потерять полностью."],
        ["3. Право на использование",
         "Использовать интерфейс можно, только если вам исполнилось 18 лет (или вы достигли совершеннолетия в своей юрисдикции), вы полностью дееспособны и получаете доступ из юрисдикции — и являетесь её резидентом, — где такое использование законно. Вы заявляете, что не находитесь под санкциями каких-либо соответствующих органов (включая списки OFAC, ООН, ЕС и Великобритании) и не включены в списки запрещённых лиц. Вы сами отвечаете за законность использования интерфейса для вас."],
        ["4. Запрещённые юрисдикции",
         "Интерфейс не предлагается и не может использоваться лицами, которые являются гражданами, резидентами или находятся на территории Соединённых Штатов Америки или их территорий, либо в любой стране или регионе под всеобъемлющими санкциями (включая, среди прочего, Кубу, Иран, Северную Корею, Сирию, а также Крым, Донецкую и Луганскую области), либо в любой иной юрисдикции, где доступ к интерфейсу или торговля этими токенами запрещены или требуют регистрации/лицензии, которой у нас нет («Запрещённые юрисдикции»). Запрещено использовать VPN, прокси или иные средства сокрытия местоположения для доступа из Запрещённой юрисдикции. Мы можем блокировать доступ из любой юрисдикции по своему усмотрению."],
        ["5. Не инвестиционный совет; не предложение",
         "Ничто на платформе не является инвестиционной, финансовой, юридической, налоговой или бухгалтерской консультацией, рекомендацией, побуждением или предложением купить либо продать какой-либо актив и не является проспектом, документом о размещении или зарегистрированным предложением ценных бумаг. Токены, запускаемые через hood, создаются пользователями, а не hood, и не одобряются, не проверяются, не гарантируются и не обеспечиваются hood. Рейтинги, аналитика, раздел «в тренде» и любое выделение в интерфейсе носят исключительно информационный характер и не являются одобрением. Оценка выгод и рисков любой операции — исключительно ваша ответственность; консультируйтесь с собственными квалифицированными специалистами."],
        ["6. Спекулятивные активы — без внутренней ценности",
         "Токены, запускаемые и торгуемые через hood, — крайне спекулятивные цифровые предметы без внутренней ценности и без каких-либо прав собственности, доли, выручки или требований к hood, его оператору или иному лицу. Если торговая пара токена запрограммирована передавать часть комиссий сделок его холдерам (раздел 18), это механическая функция смарт-контракта, которая питается только торговлей — а её может и не быть, — и не обещание прибыли, дохода или отдачи. Большинство таких токенов теряют всю или почти всю стоимость, часто стремительно. Их цена может обнулиться в любой момент. Не покупайте токен, если не готовы и не можете потерять всю сумму. Вы принимаете полную ответственность за свои торговые решения и их результаты."],
        ["7. Некастодиальный интерфейс",
         "hood никогда не хранит и не контролирует ваши активы, приватные ключи и кошельки и не имеет к ним доступа. Все операции исполняются смарт-контрактами в блокчейне и инициируются вами через ваш собственный кошелёк. Мы не можем провести, отменить, заблокировать или ускорить транзакцию за вас. Вы не являетесь нашим клиентом, и между вами и hood не возникает фидуциарных, агентских, советнических или доверительных отношений."],
        ["8. Кошельки и безопасность",
         "Вы единолично отвечаете за сохранность кошелька, приватных ключей и сид-фразы. hood никогда их не запрашивает — любой, кто просит, мошенник. Любое действие, подписанное вашим кошельком, считается вашим действием; мы не отвечаем за убытки из-за компрометации доступа к кошельку, фишинга, вредоносного ПО или ваших собственных ошибок."],
        ["9. Транзакции",
         "Проверяйте каждую транзакцию — адреса, суммы, сеть — до подписания. Цены и котировки в интерфейсе являются оценками: итоговый результат определяет смарт-контракт в момент исполнения, и он может отличаться (в том числе из-за транзакций других пользователей, проскальзывания или фронт-раннинга). Подтверждённые транзакции в блокчейне необратимы и не могут быть отменены или возвращены никем, включая hood. Когда вы платите ETH за токен, кривая которого оценивается в другом активе, вспомогательный контракт сначала меняет ваш ETH на этот актив на сторонней децентрализованной бирже, а затем совершает сделку на кривой в той же транзакции (при продаже — в обратном порядке); сумма, которую вы получите, зависит от ликвидности этой биржи в момент исполнения, а оценки, которые интерфейс показывает в пересчёте на ETH и доллары, приводятся только для удобства."],
        ["10. Запуск токенов и контент",
         "Запуская токен, вы единолично отвечаете за его название, тикер, описание, картинку и ссылки и подтверждаете, что обладаете необходимыми правами на них, что они не нарушают прав третьих лиц, не выдают себя за какое-либо лицо или бренд и не нарушают закон. Метаданные токена записываются в публичный блокчейн навсегда — их не может изменить или удалить никто, включая hood. Мы можем модерировать офчейн-контент (например, чат) и скрывать из интерфейса листинги, нарушающие эти Условия, но не можем менять ончейн-записи. Страницы, которые ИИ-агент монеты строит по идеям холдеров, размещает hood; мы можем редактировать, скрывать или удалять их по своему усмотрению."],
        ["11. Торговля на кривой и градация",
         "Токены торгуются на автоматической бондинг-кривой до порога градации, после чего ликвидность мигрирует на децентрализованную биржу и запирается. Токены могут иметь низкую ликвидность или не иметь её, быть крайне волатильными и полностью обесцениться. hood не гарантирует градацию, ликвидность, глубину рынка, возможность продажи или какой-либо уровень цены любого токена."],
        ["12. Раскрытие рисков",
         "Используя интерфейс, вы принимаете риски блокчейн-технологий, включая: полную потерю активов; дефекты и уязвимости смарт-контрактов (которые не проходили формального независимого аудита); сбои, перегрузки, форки и реорганизации сетей, кошельков и инфраструктуры; неточность или задержку рыночных данных; ошибки, предвзятость и вредный контент в ответах моделей ИИ; мошенничество, «rug-pull» и злоупотребления со стороны других пользователей и создателей токенов; регуляторную неопределённость и будущие изменения закона; налоговые последствия ваших операций. Используйте интерфейс, только если понимаете и принимаете эти риски."],
        ["13. Комиссии, налоги и отсутствие возвратов",
         "Каждая сделка на кривой платит комиссию протокола (сейчас 1% от сделки), которую смарт-контракт делит автоматически: часть уходит создателю токена, часть — в казну арены, остальное — команде; если создатель включил ИИ-агента монеты, часть комиссии идёт в бюджет этого агента вместо создателя. Распределение фиксируется в торговой паре при создании токена и потом не меняется; токены, созданные при прежних настройках, сохраняют своё исходное распределение. Актуальное распределение для новых запусков всегда показано на странице запуска и на странице каждого токена. Для токенов с ценой в токенизированной акции или стейблкоине создатель может дополнительно задать при запуске ставку выплат холдерам — до 3% с каждой сделки (раздел 18). Вы также платите сетевые комиссии за газ, а при оплате ETH токена с ценой в другом активе — комиссии и ценовое воздействие децентрализованной биржи, через которую делается обмен. Все комиссии окончательны и не возвращаются. Казна арены — смарт-контракт без функции вывода: её баланс может тратиться только на выкуп токенов платформы с рынка и их сжигание. Раз в сутки автоматический бот распределяет накопленный баланс между подиумом Арены за прошедший день (ежедневный турнир по честному ончейн-объёму торгов, который считает открытый код по ончейн-сделкам) в пропорциях, показанных на странице Арены; выплата может быть отложена или пропущена, если рыночные данные недоступны или кривая токена закрыта, — тогда баланс переносится дальше. Выкупы не являются выплатами кому-либо, не гарантируются и не создают требований к hood. Вы единолично отвечаете за определение, декларирование и уплату любых налогов, возникающих из ваших операций."],
        ["14. Допустимое использование",
         "Запрещено использовать интерфейс для: нарушения применимого закона; мошенничества и введения пользователей в заблуждение; нарушения интеллектуальных прав или выдачи себя за других; вмешательства в работу, атак, перегрузки или обратной разработки интерфейса и контрактов; манипулирования рынком (включая wash-трейдинг, спуфинг, скоординированные пампы и «rug-pull»); отмывания средств и финансирования незаконной или террористической деятельности; запуска или торговли токенами, являющимися ценными бумагами, деривативами или иными регулируемыми инструментами в соответствующих юрисдикциях. Запрещено использовать ботов и автоматические средства для злоупотребления интерфейсом."],
        ["15. Комплаенс и противодействие отмыванию",
         "hood не содействует отмыванию денег, обходу санкций или финансированию терроризма и сознательно не работает с подсанкционными лицами. Вы заявляете, что используемые вами средства получены законно и что ваше использование соответствует всем применимым к вам законам о противодействии отмыванию, финансированию терроризма и санкционному законодательству. Мы можем применять инструменты скрининга, ограничивать или отказывать в обслуживании адресам кошельков, связанным с подсанкционными лицами, незаконной деятельностью или повышенным риском, и сообщать о деятельности органам, если этого требует закон."],
        ["16. Интересы платформы и конфликты",
         "Команда получает долю комиссий протокола, заданную в смарт-контрактах. hood и участники команды могут запускать, держать, покупать и продавать токены на платформе, включая токены, созданные командой, и включать для них ИИ-агентов. Бюджеты, накопленные для ИИ-агентов, тратятся на работу этих агентов по усмотрению платформы; мы можем оплачивать функции ИИ из собственных средств и можем прекратить это в любой момент. Функции интерфейса могут добавляться, меняться, скрываться и выводиться из продукта в любое время. Ничто в интерфейсе — рейтинги, выделенное размещение, аналитика или само наличие функции — не является рекомендацией или обещанием каких-либо будущих действий hood."],
        ["17. Запуски с ценой в токенизированных акциях",
         "Платформа может позволять запускать и торговать токены на бондинг-кривой, где ценой выступает сторонняя токенизированная акция или стейблкоин, а не нативная монета сети. Такие quote-активы выпускаются и администрируются третьими лицами, с которыми hood не связан. hood не аффилирован с Robinhood Markets, Inc., её аффилированными лицами, какой-либо биржей, публичной компанией или эмитентом токенизированных акций, не спонсируется и не одобряется ими; названия продуктов, компаний и тикеры являются товарными знаками их правообладателей и используются исключительно для идентификации соответствующего актива. Покупка токена, кривая которого номинирована в токенизированной акции, не является покупкой этой акции или доли в компании: она не даёт прав акционера, права голоса, права на дивиденды или иных экономических прав в отношении такой компании. Вы дополнительно принимаете риски самого quote-актива: дефолт эмитента или кастодиана, ограничения на погашение и передачу, отвязку от цены базового актива, сбой оракула, делистинг, приостановку торгов и действия регуляторов. Во многих юрисдикциях токенизированные акции являются регулируемыми инструментами, приобретение, владение или торговля которыми могут быть ограничены или требовать лицензии; вы единолично отвечаете за законность вашего использования и не должны пользоваться функцией, если она для вас незаконна."],
        ["18. Выплаты холдерам",
         "Токен, кривая которого оценивается в токенизированной акции или стейблкоине, может быть запущен со ставкой выплат холдерам, которую выбирает его создатель (0–3% с каждой сделки). Эта доля каждой покупки и продажи откладывается контрактом токена и начисляется холдерам пропорционально их балансам — в валюте этого токена (например, в токенизированной акции), а не в ETH; интерфейс может показывать её в пересчёте на ETH и доллары для удобства. Начисленное холдер может забрать в интерфейсе; автоматический сервис платформы также может выплачивать его на кошельки холдеров по мере возможности — запуски могут задерживаться, пропускаться или прекращаться, и в этом случае вам ничего не причитается. Выплаты существуют, только пока идёт торговля: без сделок распределять нечего, и за любой период сумма может быть нулевой. Это запрограммированная функция торговой пары — не дивиденд, не процент, не доходность и не отдача на инвестиции, не платёж hood и не распределение со стороны компании, чью акцию отслеживает валюта, и не право требования к ней. Владение токеном не даёт акционерных, голосующих или экономических прав в этой компании. Вы единолично отвечаете за то, законно ли для вас приобретение, владение и получение таких активов, и за налоговые последствия."],
        ["19. ИИ-агент монеты и доска идей",
         "Создатель токена может включить для него ИИ-агента, подписав ончейн-транзакцию; это решение необратимо, и с этого момента часть комиссии протокола, которая иначе шла бы создателю, пополняет бюджет агента (раздел 13). Холдеры такого токена могут предлагать идеи на доске идей монеты и голосовать за них весом своего баланса; автоматический агент периодически берёт лидирующую идею и строит по ней веб-страницу с помощью сторонней модели ИИ, выбранной создателем, публикуя результат на hoodandarrow.com. Идеи и голоса подписываются вашим кошельком и публичны. Агент работает по мере возможности: сборки могут не удаваться, задерживаться, пропускаться при исчерпании бюджета или получаться не такими, как предлагалось; мы можем вводить лимиты, требовать бюджет, менять модель, отклонять или удалять любую идею или страницу и приостанавливать функцию в любое время. Результаты ИИ генерируются автоматически, не проверяются hood, могут быть ошибочными, вводящими в заблуждение, нарушающими чужие права или оскорбительными и не являются заявлениями, советами или рекомендациями hood. Бюджеты, накопленные для агента, служат работе этого агента и не являются вашей собственностью или требованием."],
        ["20. Чат с ИИ монеты",
         "Если у монеты включён ИИ, её холдеры могут общаться с ним в чате, который публичен: каждый, кто открывает страницу монеты, видит все сообщения вместе с адресом кошелька автора. Чтобы писать, вы подписываете кошельком сообщение, подтверждающее владение; транзакция или оплата не нужны. Ваши сообщения и публичная информация о монете отправляются стороннему провайдеру модели ИИ для генерации ответа (см. Политику конфиденциальности). ИИ говорит от лица мемкоина: его ответы — развлечение и общая информация, а не финансовая, юридическая или налоговая консультация, не утверждения о фактах, касающихся токена, его цены или перспектив, и не обязательства hood или создателя монеты. Не действуйте на их основании без собственной проверки. Мы применяем лимиты на кошелёк и на монету, можем модерировать, скрывать и удалять сообщения, ограничивать кошельки, злоупотребляющие чатом, а также менять или прекращать функцию в любое время. Не публикуйте персональные данные, ключи и всё, что не готовы сделать общедоступным."],
        ["21. Лимиты активности",
         "Мы можем вводить лимиты на размер или частоту операций либо ограничивать отдельные функции интерфейса из соображений безопасности, управления рисками или соблюдения закона. Ончейн-лимиты (например, максимальная стартовая покупка создателя) обеспечиваются самими контрактами."],
        ["22. Сторонние сервисы",
         "Интерфейс опирается на независимые сервисы: кошельки, RPC-узлы, эксплорер, индексатор событий, API цен, контракты децентрализованной биржи, хостинг, API-шлюз чата с ИИ монеты, базу чата и провайдеров моделей ИИ, доступных через OpenRouter. Их доступность, точность и условия вне нашего контроля; интеграция не означает одобрения. Использование сторонних сервисов регулируется их собственными условиями, и мы не отвечаем за их действия или бездействие."],
        ["23. Интеллектуальная собственность и жалобы",
         "Интерфейс, его дизайн, тексты и код защищены законом. Вам предоставляется ограниченная, неисключительная, непередаваемая, отзывная лицензия на доступ к интерфейсу и его использование только в законных целях; все прочие права сохраняются за нами. Если вы считаете, что отображаемый через интерфейс контент нарушает ваши интеллектуальные права или выдаёт себя за вас, направьте уведомление на контакт из раздела 37 с указанием контента, ваших прав и контактных данных — мы рассмотрим его и при необходимости удалим офчейн-листинг (ончейн-данные изменить нельзя). Мы можем удалять контент и отключать доступ для повторных нарушителей."],
        ["24. Пользовательский контент",
         "Права на контент, который вы публикуете (метаданные токенов, сообщения чата, идеи для агента монеты, сообщения ИИ монеты), остаются за вами. Публикуя его, вы предоставляете hood всемирную безвозмездную сублицензируемую лицензию на хранение, воспроизведение и показ этого контента для работы и продвижения платформы. Вы единолично отвечаете за свой контент. Контент, записанный в блокчейн, публичен и постоянен по своей природе."],
        ["25. Обратная связь",
         "Если вы присылаете нам идеи, предложения или сообщения об ошибках, мы можем использовать их для улучшения платформы без ограничений и без вознаграждения."],
        ["26. Доступность сервиса",
         "Мы можем изменять, приостанавливать или прекращать работу любой части интерфейса в любой момент без уведомления и без ответственности. Мы не гарантируем непрерывную и безошибочную работу. Смарт-контракты остаются в блокчейне независимо от доступности интерфейса."],
        ["27. Отказ от гарантий",
         "Интерфейс предоставляется «как есть» и «как доступно», со всеми недостатками. В максимальной степени, допустимой законом, мы отказываемся от любых гарантий — явных, подразумеваемых или установленных законом, — включая товарную пригодность, соответствие определённой цели, право собственности, ненарушение прав, точность данных и бесперебойную или безопасную работу. Мы не гарантируем, что какой-либо токен имеет ценность, ликвидность или рынок. Аналитические функции — включая «честный объём», бейджи кошельков (например «снайпер», «накрутка», «кит», «свежий кошелёк»), паспорт токена и репутацию создателя — являются автоматическими эвристиками, рассчитанными из публичных он-чейн данных исключительно в информационных целях. Они могут быть неполными, запаздывать или ошибаться в любую сторону, не являются обвинением какого-либо лица в неправомерных действиях, не являются инвестиционным исследованием или советом, и на них нельзя полагаться при принятии торговых решений. Результаты функций ИИ точно так же автоматические и непроверенные."],
        ["28. Принятие риска",
         "Вы осознанно и добровольно принимаете все риски, связанные с использованием интерфейса, смарт-контрактов, блокчейн-сети и любого токена, и соглашаетесь, что hood не отвечает за любые убытки, которые вы понесёте в результате. Это принятие риска сохраняет силу после прекращения действия этих Условий."],
        ["29. Ограничение ответственности",
         "В максимальной степени, допустимой законом, hood и участники разработки не отвечают за косвенные, случайные, специальные, штрафные и последующие убытки, упущенную выгоду, потерю данных, деловой репутации или активов, возникшие из использования интерфейса, контрактов, сети, токенов или сторонних сервисов или связанные с ними, даже если о возможности таких убытков было известно. Совокупная ответственность по всем требованиям ограничена большей из сумм: комиссии протокола, уплаченные вами команде за предыдущие 12 месяцев, или 100 долларов США. В некоторых юрисдикциях отдельные ограничения не допускаются, поэтому часть этого раздела может к вам не применяться."],
        ["30. Возмещение убытков",
         "Вы обязуетесь оградить и освободить от ответственности hood и участников разработки от претензий, убытков, обязательств и расходов (включая разумные юридические издержки), возникших из вашего использования интерфейса, вашего контента, ваших токенов, нарушения вами этих Условий или закона либо нарушения вами прав третьих лиц. Споры между пользователями, а также между вами и создателем токена, решаются между этими сторонами; вы освобождаете hood от претензий, связанных с такими спорами."],
        ["31. Форс-мажор",
         "hood не отвечает за неисполнение или задержку, вызванные обстоятельствами вне нашего разумного контроля, включая стихийные бедствия, войну, терроризм, гражданские беспорядки, трудовые споры, изменения закона, действия государственных или регуляторных органов, сбои сети или блокчейна, форки, перегрузки, эксплойты, перебои в работе интернета, хостинга, RPC или сторонних сервисов, а также перебои электропитания."],
        ["32. Прекращение и ограничение доступа",
         "Мы можем ограничить или прекратить ваш доступ к интерфейсу в любой момент без уведомления в случае мошенничества, манипулирования рынком, санкционного или правового риска, нарушения этих Условий или угрозы безопасности. Ограничение доступа к интерфейсу не затрагивает ваши ончейн-активы — они остаются под контролем вашего кошелька. Положения, которые по своей природе должны сохранять силу (включая раскрытие рисков, отказы от гарантий, ограничения ответственности, возмещение убытков и разрешение споров), продолжают действовать после прекращения."],
        ["33. Применимое право",
         "Эти Условия и любой спор из них или из вашего использования интерфейса регулируются правом, применимым по месту нахождения оператора, без учёта коллизионных норм, если императивные нормы защиты потребителей вашей юрисдикции не предусматривают иное."],
        ["34. Разрешение споров; арбитраж и отказ от коллективных исков",
         "До предъявления любого формального требования вы соглашаетесь сначала попытаться урегулировать спор добросовестно, связавшись с нами (раздел 37) и дав 60 дней. Любой неурегулированный так спор в максимально допустимой законом мере разрешается окончательным и обязательным индивидуальным арбитражем, а не в суде, за исключением того, что любая сторона может обратиться в суд по мелким искам либо за обеспечительными мерами по вопросам интеллектуальной собственности или несанкционированного доступа. ВЫ И HOOD СОГЛАШАЕТЕСЬ, ЧТО ТРЕБОВАНИЯ МОГУТ ПРЕДЪЯВЛЯТЬСЯ ТОЛЬКО В ИНДИВИДУАЛЬНОМ КАЧЕСТВЕ, А НЕ В КАЧЕСТВЕ ИСТЦА ИЛИ УЧАСТНИКА ГРУППЫ В ЛЮБОМ КОЛЛЕКТИВНОМ ИЛИ ПРЕДСТАВИТЕЛЬСКОМ ПРОИЗВОДСТВЕ, И ЧТО НИ ОДИН АРБИТРАЖ ИЛИ ИСК НЕ БУДЕТ ОБЪЕДИНЁН С ДРУГИМ. Любое требование должно быть предъявлено в течение одного года после его возникновения, иначе оно безвозвратно погашается, в допустимой законом мере."],
        ["35. Общие положения",
         "Если какое-либо положение этих Условий признано неисполнимым, оно ограничивается или отделяется в минимально необходимой мере, а остальные сохраняют полную силу. Неприменение нами какого-либо права не является отказом от него. Вы не можете уступать свои права по этим Условиям без нашего согласия; мы можем уступить свои в связи с управлением платформой или её передачей. Заголовки приведены только для удобства. Эти Условия вместе с Политикой конфиденциальности составляют полное соглашение между вами и hood в отношении интерфейса."],
        ["36. Изменения условий",
         "Мы можем обновлять эти Условия по мере развития продукта. Актуальная версия с датой вступления в силу всегда доступна на этой странице; о существенных изменениях мы можем дополнительно сообщить в интерфейсе. Продолжение использования после даты вступления в силу означает согласие."],
        ["37. Контакты",
         "Вопросы по этим Условиям, а также уведомления по интеллектуальной собственности и комплаенсу: contact@hoodandarrow.com."],
      ]}
    />
  );
}
